# Generated by Django 6.0.1 on 2026-01-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_twilio_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in the POS system", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "available_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time (e.g., 06:00 for breakfast)",
                        null=True,
                    ),
                ),
                (
                    "available_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time (e.g., 11:00 for breakfast)",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in the POS system", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="restaurant.menu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "menu categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in the POS system", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="False = 86'd (unavailable)"
                    ),
                ),
                (
                    "availability_updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When availability was last updated"
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                (
                    "allergens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of allergens (e.g., ["nuts", "dairy", "shellfish"])',
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurant.menucategory",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in the POS system", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "min_selections",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum required (0 = optional)"
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum allowed (1 = single choice)"
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="restaurant.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="ID in the POS system", max_length=255
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price change when selected (can be negative)",
                        max_digits=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="restaurant.modifiergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Order ID in the POS system",
                        max_length=255,
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Requested pickup/delivery time (null = ASAP)",
                        null=True,
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                ("delivery_address", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, help_text="Stripe PaymentIntent ID", max_length=255
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When order was submitted to POS",
                        null=True,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        help_text="Customer-facing confirmation code",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_ready_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Estimated time order will be ready",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "modifiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Selected modifiers with names and price adjustments",
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="unit_price * quantity + modifier adjustments",
                        max_digits=10,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        help_text="Reference to the menu item (for analytics)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurant.order",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pos_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("toast", "Toast"),
                            ("clover", "Clover"),
                            ("square", "Square"),
                        ],
                        help_text="Connected POS system (blank = no POS)",
                        max_length=20,
                    ),
                ),
                (
                    "pos_location_id",
                    models.CharField(
                        blank=True,
                        help_text="Location ID in the POS system",
                        max_length=255,
                    ),
                ),
                (
                    "pos_connected_at",
                    models.DateTimeField(
                        blank=True, help_text="When POS was connected", null=True
                    ),
                ),
                (
                    "static_menu_json",
                    models.JSONField(
                        blank=True,
                        help_text="Manual menu JSON for clients without POS integration",
                        null=True,
                    ),
                ),
                ("show_prices", models.BooleanField(default=True)),
                ("show_descriptions", models.BooleanField(default=True)),
                ("show_images", models.BooleanField(default=True)),
                (
                    "ordering_enabled",
                    models.BooleanField(
                        default=False, help_text="Allow online ordering"
                    ),
                ),
                ("pickup_enabled", models.BooleanField(default=True)),
                ("delivery_enabled", models.BooleanField(default=False)),
                (
                    "delivery_radius_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "delivery_minimum",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Tax rate as decimal (e.g., 0.0825 for 8.25%)",
                        max_digits=5,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["client", "is_active"], name="restaurant__client__f66545_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_e10fd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["menu", "display_order"], name="restaurant__menu_id_20ac57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menucategory",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_1e460b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["client", "category"], name="restaurant__client__a57c14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["client", "is_available"], name="restaurant__client__d73fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_5e097b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modifiergroup",
            index=models.Index(
                fields=["item", "display_order"], name="restaurant__item_id_b80b84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modifiergroup",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_6de2e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["group", "display_order"], name="restaurant__group_i_ab053a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_c87b4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client", "status"], name="restaurant__client__987e9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["client", "created_at"], name="restaurant__client__03cd1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="restaurant__stripe__57f206_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["external_id"], name="restaurant__externa_5b1509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["confirmation_code"], name="restaurant__confirm_6164a7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="restaurantprofile",
            constraint=models.UniqueConstraint(
                fields=("client",), name="unique_restaurant_profile_per_client"
            ),
        ),
    ]
