/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: data-analytics
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "data-analytics",
    name: "DataFlow Analytics",
    tagline: "Turn data into decisions",
    email: "hello@dataflow-analytics.com",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/data-analytics/form",
  },
  services: [
    {
      name: "Real-time Dashboards",
      slug: "dashboards",
      description: "Live metrics and KPIs at your fingertips with customizable visualizations.",
    },
    {
      name: "Custom Reports",
      slug: "reports",
      description: "Build reports tailored to your business needs with drag-and-drop simplicity.",
    },
    {
      name: "Data Integration",
      slug: "integrations",
      description: "Connect 100+ data sources including databases, APIs, and SaaS tools.",
    },
    {
      name: "AI-Powered Insights",
      slug: "ai-insights",
      description: "Automated anomaly detection and predictive analytics powered by ML.",
    },
    {
      name: "Team Collaboration",
      slug: "collaboration",
      description: "Share dashboards, annotate insights, and align your entire organization.",
    },
    {
      name: "Enterprise Security",
      slug: "security",
      description: "SOC 2 Type II certified with SSO, audit logs, and role-based access.",
    },
  ],
  social: {
    linkedin: "https://linkedin.com/company/dataflow-analytics",
    twitter: "https://twitter.com/dataflowHQ",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Features", href: "/features" },
    { label: "Pricing", href: "/pricing" },
    { label: "Case Studies", href: "/case-studies" },
    { label: "Contact", href: "/contact" },
  ],
  branding: {
    primaryColor: "2563eb",
  },
};
