# Generated by Django 6.0.1 on 2026-01-21 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        ("inbox", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="inbox.contact",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="inbox.contact",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="crm.job",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.client",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="jobs", to="crm.tag"),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contact__isnull", False), ("job__isnull", False), _connector="OR"
                ),
                name="note_has_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="unique_tag_per_client"
            ),
        ),
    ]
