# Generated by Django 6.0.1 on 2026-01-23 20:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_twilio_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("toast", "Toast"),
                            ("clover", "Clover"),
                            ("square", "Square"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type from the POS system", max_length=100
                    ),
                ),
                ("payload", models.JSONField(help_text="Raw webhook payload")),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="Signature header for verification",
                        max_length=500,
                    ),
                ),
                (
                    "external_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Event ID from the POS system (for deduplication)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "processing_duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time to process webhook in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_webhook_events",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="pos_poswebh_client__fbbcac_idx",
                    ),
                    models.Index(
                        fields=["client", "received_at"],
                        name="pos_poswebh_client__0fefaf_idx",
                    ),
                    models.Index(
                        fields=["provider", "event_type"],
                        name="pos_poswebh_provide_7dc286_idx",
                    ),
                    models.Index(
                        fields=["external_event_id"],
                        name="pos_poswebh_externa_301313_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_event_id__gt", "")),
                        fields=("client", "provider", "external_event_id"),
                        name="unique_pos_webhook_event",
                    )
                ],
            },
        ),
    ]
