/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: landscaper
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "landscaper",
    name: "Green Thumb Landscaping",
    tagline: "Transform your outdoor space",
    phone: "(555) 123-4567",
    email: "hello@greenthumblandscaping.com",
    address: "123 Main St, City, ST 12345",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/landscaper/form",
  },
  services: [
    {
      name: "Lawn Maintenance",
      slug: "lawn-maintenance",
      description:
        "Professional mowing, edging, fertilization, and weed control to keep your lawn looking its best year-round.",
    },
    {
      name: "Landscape Design & Installation",
      slug: "landscape-design",
      description:
        "Custom landscape designs brought to life. From concept to completion, we create outdoor spaces you'll love.",
    },
    {
      name: "Tree & Shrub Care",
      slug: "tree-shrub-care",
      description:
        "Expert pruning, trimming, and care for trees and shrubs. Keep your plants healthy and beautifully shaped.",
    },
    {
      name: "Irrigation Systems",
      slug: "irrigation",
      description:
        "Installation, repair, and maintenance of sprinkler and drip irrigation systems for efficient watering.",
    },
    {
      name: "Hardscaping",
      slug: "hardscaping",
      description:
        "Patios, walkways, retaining walls, and outdoor living spaces built to last with quality materials.",
    },
    {
      name: "Seasonal Cleanup",
      slug: "seasonal-cleanup",
      description:
        "Spring preparation, fall cleanup, leaf removal, and winterization services to keep your property pristine.",
    },
  ],
  social: {
    // Add your social links
    // facebook: "https://facebook.com/...",
    // instagram: "https://instagram.com/...",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Gallery", href: "/gallery" },
    { label: "Contact", href: "/contact" },
  ],
  branding: {
    primaryColor: "166534",
  },
};
