/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: cleaning
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "cleaning",
    name: "Sparkle Clean Co",
    tagline: "Professional cleaning, sparkling results",
    phone: "(555) 123-4567",
    email: "hello@sparklecleanco.com",
    address: "123 Main St, City, ST 12345",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/cleaning/form",
  },
  services: [
    {
      name: "Regular House Cleaning",
      slug: "regular-house-cleaning",
      description:
        "Weekly or bi-weekly cleaning to keep your home fresh and tidy. Dusting, vacuuming, mopping, and more.",
    },
    {
      name: "Deep Cleaning",
      slug: "deep-cleaning",
      description:
        "Thorough top-to-bottom cleaning for when your home needs extra attention. Perfect for seasonal refreshes.",
    },
    {
      name: "Move In/Out Cleaning",
      slug: "move-cleaning",
      description:
        "Comprehensive cleaning for moving transitions. Leave your old place spotless or start fresh in your new home.",
    },
    {
      name: "Office Cleaning",
      slug: "office-cleaning",
      description:
        "Professional cleaning for offices and workspaces. Keep your team healthy and productive.",
    },
    {
      name: "Post-Construction Cleanup",
      slug: "post-construction",
      description:
        "Specialized cleaning after renovations or construction. We remove dust, debris, and get your space move-in ready.",
    },
  ],
  social: {
    // Add your social links
    // facebook: "https://facebook.com/...",
    // instagram: "https://instagram.com/...",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Pricing", href: "/pricing" },
    { label: "Contact", href: "/contact" },
  ],
  branding: {
    primaryColor: "059669",
  },
};
