# Generated by Django 6.0.1 on 2026-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, help_text="Service/mailing address"),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated message summary"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_new_lead",
            field=models.BooleanField(
                default=False, help_text="AI determined this is a new lead"
            ),
        ),
    ]
