# Generated by Django 6.0.1 on 2026-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_add_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_id',
            field=models.CharField(blank=True, help_text='External provider message ID (Twilio SID, etc.)', max_length=100),
        ),
    ]
