/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: local-agency
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "local-agency",
    name: "Consult Local",
    tagline: "Your business, online in days",
    email: "hello@consultlocal.io",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/local-agency/form",
  },
  services: [
    {
      name: "Website Design & Development",
      slug: "website-design",
      description:
        "Professional, mobile-friendly websites that make your business look great online.",
    },
    {
      name: "Online Booking Integration",
      slug: "booking",
      description:
        "Let customers book appointments directly from your website, 24/7.",
    },
    {
      name: "Contact Form & Lead Capture",
      slug: "lead-capture",
      description:
        "Never miss a lead with smart forms that capture inquiries and notify you instantly.",
    },
    {
      name: "Mobile-Optimized Design",
      slug: "mobile",
      description:
        "Your site looks and works perfectly on phones, tablets, and desktops.",
    },
    {
      name: "SEO Fundamentals",
      slug: "seo",
      description:
        "Get found on Google with built-in search engine optimization best practices.",
    },
    {
      name: "Ongoing Support",
      slug: "support",
      description:
        "We're here when you need us - updates, changes, and questions answered.",
    },
  ],
  social: {
    linkedin: "https://linkedin.com/company/consult-local",
    facebook: "https://facebook.com/consultlocal",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "How It Works", href: "/how-it-works" },
    { label: "Pricing", href: "/pricing" },
    { label: "Contact", href: "/contact" },
  ],
  branding: {
    primaryColor: "1e40af", // Blue
  },
};
