/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: barber
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "barber",
    name: "Classic Cuts Barbershop",
    tagline: "Where tradition meets style",
    phone: "(555) 123-4567",
    email: "hello@barber.com",
    address: "123 Main St, City, ST 12345",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/barber/form",
  },
  services: [
    {
      name: "Classic Haircut",
      slug: "classic-haircut",
      description: "Traditional scissor cut with hot towel finish. $25",
    },
    {
      name: "Fade / Taper",
      slug: "fade",
      description: "Modern fade or taper with clean lines. $30",
    },
    {
      name: "Beard Trim",
      slug: "beard-trim",
      description: "Professional shaping and trimming. $15",
    },
    {
      name: "Hot Towel Shave",
      slug: "hot-towel-shave",
      description: "Traditional straight razor experience. $35",
    },
    {
      name: "Haircut + Beard Combo",
      slug: "combo",
      description: "Full service cut and beard grooming. $40",
    },
    {
      name: "Kids Cut",
      slug: "kids-cut",
      description: "Cuts for kids 12 and under. $18",
    },
  ],
  social: {
    instagram: "https://instagram.com/classiccutsbarbershop",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Book Now", href: "/book" },
    { label: "Contact", href: "/contact" },
  ],
  calcom: {
    username: "classiccuts",
    eventSlug: "haircut",
    brandColor: "d97706",
  },
  branding: {
    primaryColor: "d97706",
  },
};
