# Generated by Django 6.0.1 on 2026-01-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_twilio_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("jobber", "Jobber"), ("calcom", "Cal.com")],
                        max_length=50,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("webhook_secret", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("external_account_id", models.CharField(blank=True, max_length=100)),
                ("external_account_name", models.CharField(blank=True, max_length=200)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "provider"),
                        name="unique_integration_per_client_provider",
                    )
                ],
            },
        ),
    ]
