# Generated by Django 6.0.1 on 2026-01-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="vertical",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("junk_hauler", "Junk Hauler"),
                    ("barber", "Barber"),
                    ("cleaning", "Cleaning Service"),
                    ("landscaper", "Landscaper"),
                    ("coffee_shop", "Coffee Shop"),
                    ("restaurant", "Restaurant"),
                    ("data_analytics", "Data Analytics"),
                    ("web_dev", "Web Development"),
                    ("local_agency", "Local Agency"),
                ],
                default="general",
                help_text="Business vertical for AI classification context",
                max_length=50,
            ),
        ),
    ]
