# Generated by Django 6.0.1 on 2026-01-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_client_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='twilio_phone',
            field=models.CharField(blank=True, help_text='Twilio phone number for SMS (e.g., +15551234567)', max_length=20),
        ),
    ]
