/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: hauler
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "hauler",
    name: "Quick Haul Co",
    tagline: "Same-day junk removal, no hassle",
    phone: "(555) 123-4567",
    email: "hello@quickhaulco.com",
    address: "123 Main St, City, ST 12345",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/hauler/form",
  },
  services: [
    {
      name: "Residential Junk Removal",
      slug: "residential-junk-removal",
      description:
        "Full-service junk removal for homes. We handle furniture, appliances, yard waste, and more.",
    },
    {
      name: "Commercial Cleanouts",
      slug: "commercial-cleanouts",
      description:
        "Office cleanouts, warehouse clearing, and business liquidation services.",
    },
    {
      name: "Construction Debris",
      slug: "construction-debris",
      description:
        "Removal of construction and renovation debris. Drywall, lumber, concrete, and more.",
    },
    {
      name: "Appliance Disposal",
      slug: "appliance-disposal",
      description:
        "Safe and eco-friendly disposal of refrigerators, washers, dryers, and other appliances.",
    },
    {
      name: "Estate Cleanouts",
      slug: "estate-cleanouts",
      description:
        "Compassionate and thorough estate cleanout services. We handle everything with care.",
    },
  ],
  social: {
    // Add your social links
    // facebook: "https://facebook.com/...",
    // instagram: "https://instagram.com/...",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Pricing", href: "/pricing" },
    { label: "Book Now", href: "/book" },
    { label: "Contact", href: "/contact" },
  ],
  calcom: {
    username: "quickhaul",
    eventSlug: "pickup",
    brandColor: "1d4ed8",
  },
  branding: {
    primaryColor: "1d4ed8",
  },
};
