/**
 * Site Configuration
 *
 * This file defines all site-specific configuration.
 * Generated by scripts/new-site.sh
 */

export interface SiteConfig {
  client: {
    slug: string;
    name: string;
    tagline: string;
    phone?: string;
    email: string;
    address?: string;
  };
  intake: {
    formUrl: string;
  };
  services: Array<{
    name: string;
    slug: string;
    description: string;
    icon?: string;
  }>;
  social: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
  };
  nav: Array<{
    label: string;
    href: string;
  }>;
  // Cal.com integration (optional)
  calcom?: {
    username: string;
    eventSlug: string;
    /** Brand color (hex without #, e.g., "4f46e5") */
    brandColor?: string;
  };
  // Branding (optional, for integrations)
  branding?: {
    /** Primary brand color (hex without #) */
    primaryColor?: string;
  };
}

// ============================================================================
// SITE CONFIGURATION: webstudio
// ============================================================================

export const config: SiteConfig = {
  client: {
    slug: "webstudio",
    name: "Pixel Perfect Studios",
    tagline: "Crafting digital experiences",
    email: "hello@pixelperfect.studio",
  },
  intake: {
    // Worker endpoint for form submissions
    formUrl: "https://intake.consult.io/webstudio/form",
  },
  services: [
    {
      name: "Custom Web Development",
      slug: "custom-web-development",
      description:
        "Bespoke websites built from the ground up to match your unique brand and business needs.",
    },
    {
      name: "E-commerce Solutions",
      slug: "ecommerce-solutions",
      description:
        "Powerful online stores with seamless checkout, inventory management, and payment processing.",
    },
    {
      name: "Web Application Development",
      slug: "web-applications",
      description:
        "Full-stack web applications with modern frameworks, APIs, and cloud infrastructure.",
    },
    {
      name: "UI/UX Design",
      slug: "ui-ux-design",
      description:
        "User-centered design that creates intuitive, beautiful interfaces people love to use.",
    },
    {
      name: "Website Maintenance",
      slug: "maintenance",
      description:
        "Ongoing support, updates, security patches, and performance monitoring for your site.",
    },
    {
      name: "Performance Optimization",
      slug: "performance",
      description:
        "Speed up your existing site with caching, image optimization, and Core Web Vitals improvements.",
    },
  ],
  social: {
    linkedin: "https://linkedin.com/company/pixelperfect-studios",
    twitter: "https://twitter.com/pixelperfectdev",
    instagram: "https://instagram.com/pixelperfect.studio",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Process", href: "/process" },
    { label: "Contact", href: "/contact" },
  ],
  branding: {
    primaryColor: "ec4899", // Pink
  },
};
